// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// unnamed API: Application Media Types
//
// Command:
// $ goagen
// --design=github.com/m0a/goagooglelogin/example/design
// --out=$(GOPATH)/src/github.com/m0a/goagooglelogin/example
// --version=v1.2.0-dirty

package client

import (
	"net/http"
)

// GoaExamplesSecuritySecure media type (default view)
//
// Identifier: application/vnd.goa.examples.security.secure+json; view=default
type GoaExamplesSecuritySecure struct {
	Email *string `form:"Email,omitempty" json:"Email,omitempty" xml:"Email,omitempty"`
	Image *string `form:"Image,omitempty" json:"Image,omitempty" xml:"Image,omitempty"`
	Name  *string `form:"Name,omitempty" json:"Name,omitempty" xml:"Name,omitempty"`
}

// DecodeGoaExamplesSecuritySecure decodes the GoaExamplesSecuritySecure instance encoded in resp body.
func (c *Client) DecodeGoaExamplesSecuritySecure(resp *http.Response) (*GoaExamplesSecuritySecure, error) {
	var decoded GoaExamplesSecuritySecure
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// The common media type to all request responses for this example (default view)
//
// Identifier: application/vnd.goa.examples.security.success; view=default
type Success struct {
	// Always true
	OK bool `form:"ok" json:"ok" xml:"ok"`
}

// DecodeSuccess decodes the Success instance encoded in resp body.
func (c *Client) DecodeSuccess(resp *http.Response) (*Success, error) {
	var decoded Success
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
