// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// unnamed API: Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/m0a/goagooglelogin/examples/simple/design
// --out=$(GOPATH)/src/github.com/m0a/goagooglelogin/examples/simple
// --version=v1.3.0

package app
