// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// unnamed API: Application User Types
//
// Command:
// $ goagen
// --design=github.com/m0a/goagooglelogin/example/design
// --out=$(GOPATH)/src/github.com/m0a/goagooglelogin/example
// --version=v1.2.0-dirty

package app
